framework:
    secret: ThisTokenIsNotSoSecretChangeIt
    router: { resource: ~ }
    templating: { engines: [twig] }

doctrine:
    dbal:
        driver: pdo_sqlite
        memory: true
    orm:
        entity_managers:
            default:
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                auto_mapping: true

jms_di_extra:
    locations:
        directories: ["%kernel.root_dir%/../../Twig"]

stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            timestampable: true
            loggable: true
            softdeleteable: true
